\ProvidesClass{BeamerGeomaticaUA}[15/01/2015]

\LoadClass[pdf]{beamer}


%%Packages SIEMPRE útiles
\usepackage[utf8x]{inputenc}
\usepackage[english,spanish]{babel}
\usepackage{graphics}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}

%%Enlaces con colores adaptados a los del theme
\usepackage{hyperref}
\hypersetup{
  colorlinks,
  citecolor=red,
  linkcolor=white,
  urlcolor=blue}

%%Necesarios para algunos estilos
\usepackage{color}
\usepackage{xcolor}

%%Palabras clave al castellano
\renewcommand{\tablename}{Tabla}
\renewcommand{\bibname}{Referencias}